// <auto-generated />
using System;
using EFUygulamaSınavıGrup3.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFUygulamaSınavıGrup3.Migrations
{
    [DbContext(typeof(AlbumDbContext))]
    partial class AlbumDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFUygulamaSınavıGrup3.Entities.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CikisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Durumu")
                        .HasColumnType("bit");

                    b.Property<double>("Fiyat")
                        .HasColumnType("float");

                    b.Property<double?>("IndirimOrani")
                        .HasColumnType("float");

                    b.Property<int>("YoneticiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("YoneticiId");

                    b.ToTable("Albumler");
                });

            modelBuilder.Entity("EFUygulamaSınavıGrup3.Entities.Yonetici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Yoneticiler");
                });

            modelBuilder.Entity("EFUygulamaSınavıGrup3.Entities.Album", b =>
                {
                    b.HasOne("EFUygulamaSınavıGrup3.Entities.Yonetici", "Yonetici")
                        .WithMany("Albumler")
                        .HasForeignKey("YoneticiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Yonetici");
                });

            modelBuilder.Entity("EFUygulamaSınavıGrup3.Entities.Yonetici", b =>
                {
                    b.Navigation("Albumler");
                });
#pragma warning restore 612, 618
        }
    }
}
